# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/11_msmarco-config-file.ipynb.

# %% auto 0
__all__ = ['get_config_key', 'get_msmarco_config', 'parse_args']

# %% ../nbs/11_msmarco-config-file.ipynb 2
import json, os, argparse
from typing import Optional

from xcai.config import PARAM

# %% ../nbs/11_msmarco-config-file.ipynb 4
def get_config_key(model:Optional[str]='', entity_type:Optional[str]='', suffix:Optional[str]=''):
    key = 'data'
    if len(entity_type): key = f'{key}_{entity_type}'
    if len(model): key = f'{key}-{model}'
    if len(suffix): key = f'{key}_{suffix}'
    return key
    

# %% ../nbs/11_msmarco-config-file.ipynb 5
def get_msmarco_config(data_dir, model:Optional[str]='', entity_type:Optional[str]='', suffix:Optional[str]=''):
    config_key = get_config_key(model, entity_type, suffix)
    
    mat_suffix = f'_{suffix}' if len(suffix) else ''
    raw_suffix = f'.{suffix}' if len(suffix) else ''
    return {
        config_key: {
            "path": {
                "train": {
                    "data_lbl": f"{data_dir}/trn_X_Y{mat_suffix}.npz",
                    "data_info": f"{data_dir}/raw_data/train.raw.txt",
                    "lbl_info": f"{data_dir}/raw_data/label{raw_suffix}.raw.txt",
                    "ent_meta": {
                        "prefix": "ent",
                        "data_meta": f"{data_dir}/{entity_type}_{model}_trn_X_Y.npz",
                        "lbl_meta": f"{data_dir}/{entity_type}_{model}_lbl_X_Y{mat_suffix}.npz",
                        "meta_info": f"{data_dir}/raw_data/{entity_type}_{model}.raw.txt"
                    }
                },
                "test": {
                    "data_lbl": f"{data_dir}/tst_X_Y{mat_suffix}.npz",
                    "data_info": f"{data_dir}/raw_data/test.raw.txt",
                    "lbl_info": f"{data_dir}/raw_data/label{raw_suffix}.raw.txt",
                    "ent_meta": {
                        "prefix": "ent",
                        "data_meta": f"{data_dir}/{entity_type}_{model}_tst_X_Y.npz",
                        "lbl_meta": f"{data_dir}/{entity_type}_{model}_lbl_X_Y{mat_suffix}.npz",
                        "meta_info": f"{data_dir}/raw_data/{entity_type}_{model}.raw.txt"
                    }
                }
            },
            "parameters": PARAM,
        }
    }

# %% ../nbs/11_msmarco-config-file.ipynb 6
def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--data_dir', type=str, required=True)
    parser.add_argument('--model', type=str, required=True)
    parser.add_argument('--entity_type', type=str, required=True)
    parser.add_argument('--suffix', type=str, default='')
    return parser.parse_args()
    

# %% ../nbs/11_msmarco-config-file.ipynb 8
if __name__ == '__main__':
    args = parse_args()
    
    config = get_msmarco_config(args.data_dir, args.model, args.entity_type, args.suffix)
    os.makedirs(f'{args.data_dir}/configs/', exist_ok=True)

    config_key = get_config_key(args.model, args.entity_type, args.suffix)
    with open(f'{args.data_dir}/configs/{config_key}.json', 'w') as file:
        json.dump(config, file, indent=4)
        
