# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/15_wikipedia-config-file.ipynb.

# %% auto 0
__all__ = ['get_wikipedia_config', 'parse_args']

# %% ../nbs/15_wikipedia-config-file.ipynb 2
import json, os, argparse
from xcai.config import PARAM

# %% ../nbs/15_wikipedia-config-file.ipynb 4
def get_wikipedia_config(data_dir, metadata_type=''):
    if len(metadata_type): metadata_type = f'_{metadata_type}'

    key = f"data{metadata_type}"
    config = {
        key : {
            "path": {
                "train": {
                    "data_lbl": f"{data_dir}/trn_X_Y.npz",
                    "data_info": f"{data_dir}/raw_data/train.raw.txt",
                    "lbl_info": f"{data_dir}/raw_data/label.raw.txt",
                    "data_lbl_filterer": f"{data_dir}/filter_labels_train.txt",
                    "cat_meta": {
                        "prefix": "cat",
                        "data_meta": f"{data_dir}/category_trn_X_Y.npz",
                        "lbl_meta": f"{data_dir}/category_lbl_X_Y.npz",
                        "meta_info": f"{data_dir}/raw_data/category.raw.txt"
                    }
                },
                "test": {
                    "data_lbl": f"{data_dir}/tst_X_Y.npz",
                    "data_info": f"{data_dir}/raw_data/test.raw.txt",
                    "lbl_info": f"{data_dir}/raw_data/label.raw.txt",
                    "data_lbl_filterer": f"{data_dir}/filter_labels_test.txt",
                    "cat_meta": {
                        "prefix": "cat",
                        "data_meta": f"{data_dir}/category_tst_X_Y.npz",
                        "lbl_meta": f"{data_dir}/category_lbl_X_Y.npz",
                        "meta_info": f"{data_dir}/raw_data/category.raw.txt"
                    }
                }
            },
            "parameters": PARAM,
        }
    }
    
    if len(metadata_type) == 0:
        del config[key]['path']['train']['cat_meta']
        del config[key]['path']['test']['cat_meta']

    return config
    

# %% ../nbs/15_wikipedia-config-file.ipynb 5
def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--data_dir', type=str, required=True)
    parser.add_argument('--metadata_type', type=str, default='')
    return parser.parse_args()
    

# %% ../nbs/15_wikipedia-config-file.ipynb 7
if __name__ == '__main__':
    args = parse_args()
    
    config = get_wikipedia_config(args.data_dir, args.metadata_type)
    os.makedirs(f'{args.data_dir}/configs/', exist_ok=True)

    metadata_type = f'_{args.metadata_type}' if len(args.metadata_type) else ''
    with open(f'{args.data_dir}/configs/data{metadata_type}.json', 'w') as file:
        json.dump(config, file, indent=4)
        
