# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/18_map-amazon-meta-from-dump.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/18_map-amazon-meta-from-dump.ipynb 2
from timeit import default_timer as timer

from .map_amazon_dump import *

# %% ../nbs/18_map-amazon-meta-from-dump.ipynb 3
if __name__ == '__main__':
    start_time = timer()

    args = parse_args()

    trn_mat, tst_mat, lbl_mat, metadata_ids, metadata_txt = get_metadata(args.cache_dir, args.data_dir, meta_type=args.metadata_type, 
                                                                         key=args.key, condition_type=args.condition_type, 
                                                                         do_filter=args.no_filter)
    save_metadata(args.data_dir, trn_mat, tst_mat, lbl_mat, metadata_ids, metadata_txt, args.metadata_type)
    
    end_time = timer()
    print(f'Time elapsed: {end_time-start_time:.2f} seconds.')
