# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/19_map-amazon-meta-from-gpt-generations.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/19_map-amazon-meta-from-gpt-generations.ipynb 2
import pandas as pd, re, numpy as np, os
from tqdm.auto import tqdm
