# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/24_msmarco-hard-negatives-systems.ipynb.

# %% auto 0
__all__ = ['load_negatives_system_info']

# %% ../nbs/24_msmarco-hard-negatives-systems.ipynb 2
import pickle, scipy.sparse as sp, numpy as np, argparse, os, json
from tqdm.auto import tqdm
from typing import Optional, List

from xcai.main import *
from .core import *

# %% ../nbs/24_msmarco-hard-negatives-systems.ipynb 5
def load_negatives_system_info(fname):
    negatives, systems = {}, {}
    with open(fname) as file:
        for line in file:
            c = json.loads(line)
            for k,v in c['neg'].items():
                sys_id = systems.setdefault(k, len(systems))
                negatives[c['qid']] = {o:sys_id for o in v}
    return systems, negatives
                
