# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/25_msmarco-substring.ipynb.

# %% auto 0
__all__ = ['save_raw', 'load_raw', 'convert_df_to_query_dict', 'get_substring_matrix_from_query_dict',
           'get_substring_matrix_from_dict', 'get_metadata_matrix_from_dict', 'extract_substring', 'save_substring',
           'parse_args']

# %% ../nbs/25_msmarco-substring.ipynb 2
import pandas as pd, ast, numpy as np, os, json, argparse
from typing import Optional, List, Dict
from tqdm.auto import tqdm
import scipy.sparse as sp

from .core import *

# %% ../nbs/25_msmarco-substring.ipynb 4
def save_raw(fname:str, ids:List, txt:List):
    df = pd.DataFrame({"identifier": ids, "text": txt})
    df.to_csv(fname, index=False)

def load_raw(fname:str):
    df = pd.read_csv(fname, keep_default_na=False, na_filter=False)
    return df["identifier"].tolist(), df["text"].tolist()
    

# %% ../nbs/25_msmarco-substring.ipynb 6
def convert_df_to_query_dict(df):
    outputs = dict()
    
    for i in tqdm(range(df.shape[0])):
        row = df.iloc[i]
        
        query_id, label_id = row["id"], row["document_id"]
        query, label, substring = row["query"], row["document"], row["raw_model_response"]
        
        try:
            substring = ast.literal_eval(substring)
        except:
            raise ValueError(f"Error occurred while processing line {i}.")

        o = {
            "query_id": query_id, 
            "query_text": query,
            "label_id": [],
            "label_text": [],
            "substring":[],
        }
        
        o = outputs.setdefault(str(query_id), o)
        o["substring"].append(substring)
        o["label_id"].append(label_id)
        o["label_text"].append(label)
        
    return outputs
    

# %% ../nbs/25_msmarco-substring.ipynb 8
def get_substring_matrix_from_query_dict(outputs:Dict, query_ids:List, vocab:Optional[Dict]=None, 
                                         lbl_substr:Optional[Dict]=None, phrases:Optional[Dict]=None):
    if vocab is None: vocab = dict()
    
    if phrases is None: phrases = dict()
    if lbl_substr is None: lbl_substr = dict()

    data, indices, indptr = [], [], [0]
    for q in tqdm(query_ids, total=len(query_ids)):
        o = outputs.get(q, {})

        generations = o.get("substring", [])
        lbl_ids = o.get("label_id", [])

        assert len(generations) == len(lbl_ids)
        
        for gens, l in zip(generations, lbl_ids):
            for s in gens:                
                idx = vocab.setdefault(s["original_substring"], len(vocab))
                indices.append(idx)
                data.append(1.0)

                lbl_substr.setdefault(l, []).append(idx)
                phrases.setdefault(idx, []).extend(s["derived_phrases"])
                
        indptr.append(len(indices))

    qry_substr = sp.csr_matrix((data, indices, indptr), dtype=np.float32)

    return qry_substr, vocab, lbl_substr, phrases
    

# %% ../nbs/25_msmarco-substring.ipynb 9
def get_substring_matrix_from_dict(substrs:Dict, ids:List):
    data, indices, indptr = [], [], [0]
    for i in tqdm(ids):
        idxs = substrs.get(i, [])
        indices.extend(idxs)
        data.extend([1.0] * len(idxs))
        indptr.append(len(data))
    return sp.csr_matrix((data, indices, indptr), dtype=np.float32)
    

# %% ../nbs/25_msmarco-substring.ipynb 10
def get_metadata_matrix_from_dict(metadata:Dict, ids:List):
    vocab, data, indices, indptr = dict(), [], [], [0]
    for i in tqdm(ids):
        indices.extend([vocab.setdefault(o, len(vocab)) for o in metadata[i]])
        data.extend([1.0] * len(metadata[i]))
        indptr.append(len(indices))
    return sp.csr_matrix((data, indices, indptr), dtype=np.float32), vocab
    

# %% ../nbs/25_msmarco-substring.ipynb 11
def extract_substring(outputs:Dict, trn_ids:List, tst_ids:List, lbl_ids:List, seed:Optional[int]=100):
    trn_substr, substr_vocab, lbl_substr, phrases = get_substring_matrix_from_query_dict(outputs, trn_ids)

    o = get_substring_matrix_from_query_dict(outputs, tst_ids, substr_vocab, lbl_substr=lbl_substr, phrases=phrases)
    tst_substr, substr_vocab, lbl_substr, phrases = o
    
    lbl_substr = get_substring_matrix_from_dict(lbl_substr, lbl_ids)

    substr_txt = list(map(str, sorted(substr_vocab, key=lambda x:substr_vocab[x])))
    substr_ids = list(range(len(substr_txt)))

    substr_phrase, phrase_vocab = get_metadata_matrix_from_dict(phrases, substr_ids)

    return (trn_substr, tst_substr, lbl_substr), (substr_ids, substr_txt), (substr_phrase, phrase_vocab)
    

# %% ../nbs/25_msmarco-substring.ipynb 12
def save_substring(save_dir:str, trn_substr:sp.csr_matrix, tst_substr:sp.csr_matrix, lbl_substr:sp.csr_matrix,
                   substr_ids:Dict, substr_txt:str):
    
    n_trn_substr = trn_substr.shape[1]
    
    nnz = tst_substr[:, :n_trn_substr].getnnz(axis=1)
    print(f"% of training intents in test: {100 * np.where(nnz != 0)[0].shape[0]/tst_substr.shape[0]:.4f}")

    nnz = sum(lbl_substr.getnnz(axis=1) > 0)
    print(f"# of document with intent metadata: {nnz}/{lbl_substr.shape[0]}")
    
    trn_substr.sum_duplicates()
    trn_substr.sort_indices()
    
    tst_substr.sum_duplicates()
    tst_substr.sort_indices()

    lbl_substr.sum_duplicates()
    lbl_substr.sort_indices()
    
    os.makedirs(save_dir, exist_ok=True)
    
    sp.save_npz(f"{save_dir}/substring_trn_X_Y.npz", trn_substr)
    
    sp.save_npz(f"{save_dir}/substring_tst_X_Y.npz", tst_substr[:, :n_trn_substr])
    sp.save_npz(f"{save_dir}/all-substring_tst_X_Y.npz", tst_substr)

    sp.save_npz(f"{save_dir}/substring_lbl_X_Y.npz", lbl_substr[:, :n_trn_substr])
    sp.save_npz(f"{save_dir}/all-substring_lbl_X_Y.npz", lbl_substr)
    
    os.makedirs(f"{save_dir}/raw_data/", exist_ok=True)
    save_raw(f"{save_dir}/raw_data/substring.raw.csv", substr_ids[:n_trn_substr], substr_txt[:n_trn_substr])
    save_raw(f"{save_dir}/raw_data/all-substring.raw.csv", substr_ids, substr_txt)
    

# %% ../nbs/25_msmarco-substring.ipynb 54
def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--meta_name', type=str, required=True)
    return parser.parse_known_args()[0]
    

# %% ../nbs/25_msmarco-substring.ipynb 55
if __name__ == "__main__":
    input_args = parse_args()
    
    # files
    data_dir = f"/Users/suchith720/Projects/data/beir/msmarco/XC"
    intent_file = f"/Users/suchith720/Desktop/Projects/mogicX/data/gpt_substring/{input_args.meta_name}/msmarco_{input_args.meta_name}.csv"
    
    save_dir = f"/Users/suchith720/Projects/data/beir/msmarco/XC/{input_args.meta_name}/"
    
    # load raw data
    
    trn_ids, trn_txt = load_raw_file(f"{data_dir}/raw_data/train.raw.txt")
    tst_ids, tst_txt = load_raw_file(f"{data_dir}/raw_data/test.raw.txt")
    lbl_ids, lbl_txt = load_raw_file(f"{data_dir}/raw_data/label.raw.txt")
    
    df = pd.read_csv(intent_file)
    lbl_txt2ids = {v:k for k,v in zip(lbl_ids, lbl_txt)}
    df["document_id"] = [lbl_txt2ids[o] for o in df["document"]]
    
    outputs = convert_df_to_query_dict(df)
    
    # extract metadata
    o = extract_substring(outputs, trn_ids, tst_ids, lbl_ids, seed=100)
    (trn_substr, tst_substr, lbl_substr), (substr_ids, substr_txt), (substr_phrase, phrase_vocab) = o

    # save metadata
    save_substring (save_dir, trn_substr, tst_substr, lbl_substr, substr_ids, substr_txt)
    save_substring_metadata(save_dir, substr_phrase, substr_vocab)

