# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/27_msmarco-intent-substring.ipynb.

# %% auto 0
__all__ = ['save_raw', 'load_raw', 'convert_df_to_query_dict', 'get_substring_matrix_from_query_dict',
           'get_intent_matrix_from_dict', 'get_metadata_matrix_from_dict', 'extract_intents', 'save_intents',
           'save_intent_metadata']

# %% ../nbs/27_msmarco-intent-substring.ipynb 2
import pandas as pd, ast, numpy as np, os, json, argparse
from typing import Optional, List, Dict
from tqdm.auto import tqdm
import scipy.sparse as sp

from .core import *

# %% ../nbs/27_msmarco-intent-substring.ipynb 4
def save_raw(fname:str, ids:List, txt:List):
    df = pd.DataFrame({"identifier": ids, "text": txt})
    df.to_csv(fname, index=False)

def load_raw(fname:str):
    df = pd.read_csv(fname, keep_default_na=False, na_filter=False)
    return df["identifier"].tolist(), df["text"].tolist()
    

# %% ../nbs/27_msmarco-intent-substring.ipynb 6
def convert_df_to_query_dict(df):
    outputs = dict()
    
    for i in tqdm(range(df.shape[0])):
        row = df.iloc[i]
        
        query_id, label_id = row["id"], row["document_id"]
        query, label, substring = row["query"], row["document"], row["raw_model_response"]
        
        try:
            substring = ast.literal_eval(substring)
        except:
            raise ValueError(f"Error occurred while processing line {i}.")

        o = {
            "query_id": query_id, 
            "query_text": query,
            "label_id": [],
            "label_text": [],
            "substring":[],
        }
        
        o = outputs.setdefault(str(query_id), o)
        o["substring"].append(substring)
        o["label_id"].append(label_id)
        o["label_text"].append(label)
        
    return outputs
    

# %% ../nbs/27_msmarco-intent-substring.ipynb 8
def get_substring_matrix_from_query_dict(outputs:Dict, query_ids:List, vocab:Optional[Dict]=None, lbl_intent:Optional[Dict]=None, 
                                         phrases:Optional[Dict]=None, intents:Optional[Dict]=None, substrs:Optional[Dict]=None, 
                                         seed:Optional[int]=None):
    
    if seed is not None: np.random.seed(seed)

    if vocab is None: vocab = dict()
    
    if phrases is None: phrases = dict()
    if intents is None: intents = dict()
    if substrs is None: substrs = dict()
    if lbl_intent is None: lbl_intent = dict()
        
    data, indices, indptr = [], [], [0]
    for q in tqdm(query_ids, total=len(query_ids)):
        o = outputs.get(q, {})

        generations = o.get("substring", [])
        lbl_ids = o.get("label_id", [])

        assert len(generations) == len(lbl_ids)
        
        for gens, l in zip(generations, lbl_ids):
            for s in gens:
                intent = np.random.choice(s["intent_phrases"])
                
                idx = vocab.setdefault(intent, len(vocab))
                indices.append(idx)
                data.append(1.0)

                lbl_intent.setdefault(l, []).append(idx)
                phrases.setdefault(idx, []).extend(s["derived_phrases"])
                intents.setdefault(idx, []).extend(s["intent_phrases"])
                substrs.setdefault(idx, []).append(s["original_substring"])
                
        indptr.append(len(indices))

    qry_intent = sp.csr_matrix((data, indices, indptr), dtype=np.float32)

    return qry_intent, vocab, lbl_intent, phrases, intents, substrs
    

# %% ../nbs/27_msmarco-intent-substring.ipynb 10
def get_intent_matrix_from_dict(intents:Dict, ids:List):
    data, indices, indptr = [], [], [0]
    for i in tqdm(ids):
        idxs = intents.get(i, [])
        indices.extend(idxs)
        data.extend([1.0] * len(idxs))
        indptr.append(len(data))
    return sp.csr_matrix((data, indices, indptr), dtype=np.float32)
    

# %% ../nbs/27_msmarco-intent-substring.ipynb 11
def get_metadata_matrix_from_dict(metadata:Dict, ids:List):
    vocab, data, indices, indptr = dict(), [], [], [0]
    for i in tqdm(ids):
        indices.extend([vocab.setdefault(o, len(vocab)) for o in metadata[i]])
        data.extend([1.0] * len(metadata[i]))
        indptr.append(len(indices))
    return sp.csr_matrix((data, indices, indptr), dtype=np.float32), vocab
    

# %% ../nbs/27_msmarco-intent-substring.ipynb 13
def extract_intents(outputs:Dict, trn_ids:List, tst_ids:List, lbl_ids:List, seed:Optional[int]=100):
    o = get_substring_matrix_from_query_dict(outputs, trn_ids, seed=seed)
    trn_intent, intent_vocab, lbl_intent, phrases, intents, substrs = o

    
    o = get_substring_matrix_from_query_dict(outputs, tst_ids, vocab=intent_vocab, lbl_intent=lbl_intent, 
                                             phrases=phrases, intents=intents, substrs=substrs, seed=seed)
    tst_intent, intent_vocab, lbl_intent, phrases, intents, substrs = o

    lbl_intent = get_intent_matrix_from_dict(lbl_intent, lbl_ids)

    intent_txt = list(map(str, sorted(intent_vocab, key=lambda x:intent_vocab[x])))
    intent_ids = list(range(len(intent_txt)))

    intent_phrase, phrase_vocab = get_metadata_matrix_from_dict(phrases, intent_ids)
    intent_intents, intents_vocab = get_metadata_matrix_from_dict(intents, intent_ids)
    intent_substr, substr_vocab = get_metadata_matrix_from_dict(substrs, intent_ids)

    return (trn_intent, tst_intent, lbl_intent), (intent_ids, intent_txt), (intent_phrase, phrase_vocab), (intent_intents, intents_vocab), (intent_substr, substr_vocab)
    

# %% ../nbs/27_msmarco-intent-substring.ipynb 15
def save_intents(save_dir:str, trn_intent:sp.csr_matrix, tst_intent:sp.csr_matrix, lbl_intent:sp.csr_matrix,
                 intent_ids:Dict, intent_txt:str):
    
    n_trn_intent = trn_intent.shape[1]
    
    nnz = tst_intent[:, :n_trn_intent].getnnz(axis=1)
    print(f"% of training intents in test: {100 * np.where(nnz != 0)[0].shape[0]/tst_intent.shape[0]:.4f}")

    nnz = sum(lbl_intent.getnnz(axis=1) > 0)
    print(f"# of document with intent metadata: {nnz}/{lbl_intent.shape[0]}")
    
    trn_intent.sum_duplicates()
    trn_intent.sort_indices()
    
    tst_intent.sum_duplicates()
    tst_intent.sort_indices()

    lbl_intent.sum_duplicates()
    lbl_intent.sort_indices()
    
    os.makedirs(save_dir, exist_ok=True)
    
    sp.save_npz(f"{save_dir}/intent_trn_X_Y.npz", trn_intent)
    
    sp.save_npz(f"{save_dir}/intent_tst_X_Y.npz", tst_intent[:, :n_trn_intent])
    sp.save_npz(f"{save_dir}/all-intent_tst_X_Y.npz", tst_intent)

    sp.save_npz(f"{save_dir}/intent_lbl_X_Y.npz", lbl_intent[:, :n_trn_intent])
    sp.save_npz(f"{save_dir}/all-intent_lbl_X_Y.npz", lbl_intent)
    
    os.makedirs(f"{save_dir}/raw_data/", exist_ok=True)
    save_raw(f"{save_dir}/raw_data/intent.raw.csv", intent_ids[:n_trn_intent], intent_txt[:n_trn_intent])
    save_raw(f"{save_dir}/raw_data/all-intent.raw.csv", intent_ids, intent_txt)
    

# %% ../nbs/27_msmarco-intent-substring.ipynb 16
def save_intent_metadata(save_dir:str, intent_phrase:sp.csr_matrix, phrase_vocab:Dict, intent_intents:sp.csr_matrix, 
                         intents_vocab:Dict, intent_substr:sp.csr_matrix, substr_vocab:Dict):
    
    intent_phrase.sum_duplicates()
    intent_phrase.sort_indices()
    
    intent_intents.sum_duplicates()
    intent_intents.sort_indices()

    intent_substr.sum_duplicates()
    intent_substr.sort_indices()

    os.makedirs(save_dir, exist_ok=True)

    sp.save_npz(f"{save_dir}/derived-substring_all-intent_X_Y.npz", intent_phrase)
    sp.save_npz(f"{save_dir}/derived-intent_all-intent_X_Y.npz", intent_intents)
    sp.save_npz(f"{save_dir}/substring_all-intent_X_Y.npz", intent_substr)

    def get_raw_info(vocab):
        return list(range(len(vocab))), list(map(str, sorted(vocab, key=lambda x:vocab[x])))

    os.makedirs(f"{save_dir}/raw_data/", exist_ok=True)
    
    ids, txt = get_raw_info(phrase_vocab)
    save_raw(f"{save_dir}/raw_data/all-intent_derived-substring.raw.csv", ids, txt)

    ids, txt = get_raw_info(intents_vocab)
    save_raw(f"{save_dir}/raw_data/all-intent_derived-intent.raw.csv", ids, txt)

    ids, txt = get_raw_info(substr_vocab)
    save_raw(f"{save_dir}/raw_data/all-intent_substring.raw.csv", ids, txt)
    

# %% ../nbs/27_msmarco-intent-substring.ipynb 57
if __name__ == "__main__":
    # files
    data_dir = "/Users/suchith720/Projects/data/beir/msmarco/XC"
    intent_file = "/Users/suchith720/Desktop/Projects/mogicX/data/gpt_substring/intent_substring/msmarco_intent_substring.csv"
    
    save_dir = "/Users/suchith720/Projects/data/beir/msmarco/XC/intent_substring/"
    
    # load raw data
    
    trn_ids, trn_txt = load_raw_file(f"{data_dir}/raw_data/train.raw.txt")
    tst_ids, tst_txt = load_raw_file(f"{data_dir}/raw_data/test.raw.txt")
    lbl_ids, lbl_txt = load_raw_file(f"{data_dir}/raw_data/label.raw.txt")
    
    df = pd.read_csv(intent_file)
    lbl_txt2ids = {v:k for k,v in zip(lbl_ids, lbl_txt)}
    df["document_id"] = [lbl_txt2ids[o] for o in df["document"]]
    
    outputs = convert_df_to_query_dict(df)
    
    # extract metadata
    o = extract_intents(outputs, trn_ids, tst_ids, lbl_ids, seed=100)
    (trn_intent, tst_intent, lbl_intent), (intent_ids, intent_txt), (intent_phrase, phrase_vocab), (intent_intents, intents_vocab), (intent_substr, substr_vocab) = o

    # save metadata
    save_intents(save_dir, trn_intent, tst_intent, lbl_intent, intent_ids, intent_txt)
    save_intent_metadata(save_dir, intent_phrase, phrase_vocab, intent_intents, intents_vocab, 
                         intent_substr, substr_vocab)
    
    
