# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/29_beir-intent-and-summary-metadata.ipynb.

# %% auto 0
__all__ = ['save_raw', 'load_raw', 'combine_df', 'convert_string_to_object', 'get_metadata_matrix_from_label_dict',
           'get_matrix_from_dict', 'extract_metadata', 'save_metadata', 'save_metadata_info']

# %% ../nbs/29_beir-intent-and-summary-metadata.ipynb 2
import os, json, pandas as pd, ast, scipy.sparse as sp, json_repair, numpy as np, re, joblib

from tqdm.auto import tqdm
from typing import Optional, Dict, List, Tuple

from xcai.misc import BEIR_DATASETS
from .core import *

# %% ../nbs/29_beir-intent-and-summary-metadata.ipynb 5
def save_raw(fname:str, ids:List, txt:List):
    df = pd.DataFrame({"identifier": ids, "text": txt})
    df.to_csv(fname, index=False)

def load_raw(fname:str):
    df = pd.read_csv(fname, keep_default_na=False, na_filter=False)
    return df["identifier"].tolist(), df["text"].tolist()
    

# %% ../nbs/29_beir-intent-and-summary-metadata.ipynb 7
def combine_df(dirname:str):
    files = [o for o in os.listdir(dirname) if re.match(r"UHRS_Task_docs-\d+.tsv", o)]
    files = sorted(files, key=lambda x: int(x.split("-")[1][:-4]))
    return pd.concat([pd.read_table(f"{dirname}/{f}") for f in tqdm(files)], axis=0)
    

# %% ../nbs/29_beir-intent-and-summary-metadata.ipynb 9
def convert_string_to_object(df:pd.DataFrame):
    outputs, n_outputs = {}, 0
    for idx, doc, out in tqdm(zip(df["ids"], df["document"], df["raw_model_response"]), total=df.shape[0]):
        if not pd.isna(doc) and not pd.isna(out):
            match = re.match(r"```json(.*)```", out)
            if match is not None:
                out = match[1]
                try:
                    out = json.loads(out)
                except:
                    out = json_repair.loads(out)
                
                outputs[idx] = {
                    "document": doc,
                    "concepts": out[0]["concepts"] if isinstance(out, list) else out["concepts"],
                }
                n_outputs += 1

    print(f"# of empty generations: {df.shape[0] - n_outputs}.")
    return outputs
    

# %% ../nbs/29_beir-intent-and-summary-metadata.ipynb 19
def get_metadata_matrix_from_label_dict(outputs:Dict, lbl_ids:List, seed:Optional[int]=100):
    np.random.seed(seed)

    str_info = {
        "variations": dict(), "type": dict(), "summary": dict(),
    }
    lbl_mat = {
        "vocab": dict(), "data": [], "indices": [], "indptr": [0],
    }

    for l in tqdm(lbl_ids):
        o = outputs.get(str(l), {})
        concepts = o.get("concepts", [])
        
        for concept in concepts:
            idx = lbl_mat["vocab"].setdefault(concept["concept"], len(lbl_mat["vocab"]))
            lbl_mat["indices"].append(idx)
            lbl_mat["data"].append(1.0)

            str_info["variations"].setdefault(idx, []).extend(concept["variations"])
            
            str_info["type"].setdefault(idx, []).append(concept["type"])
            str_info["summary"].setdefault(idx, []).append(concept["summary"])
            
        lbl_mat["indptr"].append(len(lbl_mat["indices"]))
        
    shape = (len(lbl_mat["indptr"]) - 1, len(lbl_mat["vocab"]))
    lbl_str = sp.csr_matrix((lbl_mat["data"], lbl_mat["indices"], lbl_mat["indptr"]), shape=shape, dtype=np.float32)
    
    return lbl_mat["vocab"], lbl_str, str_info
    

# %% ../nbs/29_beir-intent-and-summary-metadata.ipynb 20
def get_matrix_from_dict(metadata:Dict, ids:List):
    vocab, data, indices, indptr = dict(), [], [], [0]
    for i in tqdm(ids):
        indices.extend([vocab.setdefault(o, len(vocab)) for o in metadata.get(i, [])])
        data.extend([1.0] * len(metadata.get(i, [])))
        indptr.append(len(indices))
    return sp.csr_matrix((data, indices, indptr), dtype=np.float32), vocab
    

# %% ../nbs/29_beir-intent-and-summary-metadata.ipynb 27
def extract_metadata(outputs:Dict, lbl_ids:List):
    o = get_metadata_matrix_from_label_dict(outputs, lbl_ids)

    str_vocab, lbl_str, str_info = get_metadata_matrix_from_label_dict(outputs, lbl_ids)

    str_txt = sorted(str_vocab, key=lambda x:str_vocab[x])
    str_ids = list(range(len(str_txt)))
    
    assert len(intent_ids) == lbl_str.shape[1], (
        f"Concept count mismatch: expected {lbl_str.shape[1]}, got {len(intent_ids)}"
    )

    str_type, type_vocab = get_matrix_from_dict(str_info["type"], str_ids)
    str_summary, summary_vocab = get_matrix_from_dict(str_info["summary"], str_ids)
    str_variations, variations_vocab = get_matrix_from_dict(str_info["variations"], str_ids)

    str_info = (str_type, type_vocab), (str_summary, summary_vocab), (str_variations, variations_vocab)
    
    return (str_ids, str_txt, lbl_str), str_info
    

# %% ../nbs/29_beir-intent-and-summary-metadata.ipynb 29
def save_metadata(save_dir:str, concept_ids:List, concept_txt:List, lbl_concept:sp.csr_matrix):
    lbl_concept.sum_duplicates()
    lbl_concept.sort_indices()
    
    os.makedirs(save_dir, exist_ok=True)
    os.makedirs(f"{save_dir}/raw_data/", exist_ok=True)
    
    sp.save_npz(f"{save_dir}/concept_lbl_X_Y.npz", lbl_concept)
    save_raw(f"{save_dir}/raw_data/label_concept.raw.csv", concept_ids, concept_txt)
    

# %% ../nbs/29_beir-intent-and-summary-metadata.ipynb 31
def save_metadata_info(save_dir:str, str_info:Tuple):    
    (str_type, type_vocab), (str_summary, summary_vocab), (str_variations, variations_vocab) = str_info
    
    str_type.sum_duplicates()
    str_type.sort_indices()
    
    str_summary.sum_duplicates()
    str_summary.sort_indices()

    str_variations.sum_duplicates()
    str_variations.sort_indices()
    
    os.makedirs(save_dir, exist_ok=True)
    os.makedirs(f"{save_dir}/raw_data/", exist_ok=True)

    def get_raw_info(vocab):
        txt = sorted(phrase_vocab, key=lambda x: phrase_vocab[x])
        ids = list(range(len(txt)))
        return ids, txt
    
    sp.save_npz(f"{save_dir}/variations_concept_X_Y.npz", str_variations)
    ids, txt = get_raw_info(variations_vocab)
    save_raw(f"{save_dir}/raw_data/concept_variations.raw.csv", ids, txt)
    
    sp.save_npz(f"{save_dir}/type_concept_X_Y.npz", str_type)
    ids, txt = get_raw_info(type_vocab)
    save_raw(f"{save_dir}/raw_data/concept_type.raw.csv", ids, txt)

    sp.save_npz(f"{save_dir}/summary_concept_X_Y.npz", str_summary)
    ids, txt = get_raw_info(summary_vocab)
    save_raw(f"{save_dir}/raw_data/concept_summary.raw.csv", ids, txt)
    

# %% ../nbs/29_beir-intent-and-summary-metadata.ipynb 33
if __name__ == "__main__":
    output_dir = "/Users/suchith720/Downloads/outputs/"

    df = combine_df(data_dir)
    outputs = convert_string_to_object(df)

    for dataset in tqdm(BEIR_DATASETS):
        print(dataset)
        
        data_dir = f"/Users/suchith720/Projects/data/beir/{dataset}/XC/"
        lbl_ids, lbl_txt = load_raw_file(f"{data_dir}/raw_data/label.raw.csv")
        
        (str_ids, str_txt, lbl_str), str_info = extract_metadata(outputs, lbl_ids)
        
        save_dir = f"{data_dir}/document_concept_substring/"
        save_metadata(save_dir, str_ids, str_txt, lbl_str)
        save_metadata_info(save_dir, str_info)
            
